# Generated by Django 4.2.15 on 2024-09-16 14:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_rename_chat_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="chatroom_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="message",
            name="message_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="prompt",
            name="prompt_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="prompttopic",
            name="prompt_topic_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
