# Generated by Django 4.2 on 2023-05-24 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_prompt_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="last_used_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Topic Created Date",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="prompt",
            name="usage_count",
            field=models.IntegerField(default=0),
        ),
    ]
