# Generated by Django 4.2.15 on 2024-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_bot_bot_bot_bot_id_d44bce_idx_and_more'),
        ('chat', '0004_message_role_id_alter_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='bots',
            field=models.ManyToManyField(blank=True, to='bot.bot'),
        ),
    ]
