# Generated by Django 4.2 on 2024-09-15 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_prompttopic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="model_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="aivendor",
            name="vendor_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
