# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rmessage.proto\x12\x0cSHZgptServer\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n\x05\x45vent\x12)\n\x06target\x18\x01 \x01(\x0e\x32\x19.SHZgptServer.EventTarget\x12)\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x19.SHZgptServer.EventAction\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07payload\x18\x04 \x01(\t\"\x88\x01\n\x07\x43ontext\x12\x13\n\x0b\x63hatroom_id\x18\x01 \x01(\x05\x12(\n\x04role\x18\x02 \x01(\x0e\x32\x1a.SHZgptServer.ChatRoleType\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"5\n\x0b\x43hatRequest\x12&\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x15.SHZgptServer.Context\"|\n\x0c\x43hatResponse\x12-\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x18.SHZgptServer.StatusCode\x12&\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x15.SHZgptServer.Context\x12\x15\n\rstatus_detail\x18\x03 \x01(\t*1\n\nStatusCode\x12\n\n\x06UNKNOW\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02*3\n\x0c\x43hatRoleType\x12\n\n\x06SYSTEM\x10\x00\x12\x08\n\x04USER\x10\x01\x12\r\n\tASSISTANT\x10\x02*1\n\x0b\x45ventTarget\x12\x08\n\x04\x43HAT\x10\x00\x12\x0c\n\x08\x43HATROOM\x10\x01\x12\n\n\x06PROMPT\x10\x02*!\n\x0b\x45ventAction\x12\x08\n\x04SEND\x10\x00\x12\x08\n\x04PULL\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_STATUSCODE']._serialized_start = 544
    _globals['_STATUSCODE']._serialized_end = 593
    _globals['_CHATROLETYPE']._serialized_start = 595
    _globals['_CHATROLETYPE']._serialized_end = 646
    _globals['_EVENTTARGET']._serialized_start = 648
    _globals['_EVENTTARGET']._serialized_end = 697
    _globals['_EVENTACTION']._serialized_start = 699
    _globals['_EVENTACTION']._serialized_end = 732
    _globals['_EVENT']._serialized_start = 65
    _globals['_EVENT']._serialized_end = 222
    _globals['_CONTEXT']._serialized_start = 225
    _globals['_CONTEXT']._serialized_end = 361
    _globals['_CHATREQUEST']._serialized_start = 363
    _globals['_CHATREQUEST']._serialized_end = 416
    _globals['_CHATRESPONSE']._serialized_start = 418
    _globals['_CHATRESPONSE']._serialized_end = 542
# @@protoc_insertion_point(module_scope)
