# Generated by Django 4.2.15 on 2024-09-16 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_remove_apikey_model_apikey_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("TEXT", "Text"),
                        ],
                        default="TEXT",
                        max_length=32,
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("TEXT", "Text"),
                        ],
                        default="TEXT",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Modality",
                "verbose_name_plural": "Modalities",
            },
        ),
        migrations.AddField(
            model_name="aimodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aimodel",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="foundation_model_id",
            field=models.CharField(default="foundation_model", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aimodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="aivendor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aivendor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="modalities",
            field=models.ManyToManyField(
                related_name="ai_models",
                related_query_name="ai_model",
                to="bot.modality",
            ),
        ),
    ]
