# Generated by Django 4.2.15 on 2024-09-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_bot_owner_bot_bot_bot_bot_id_d44bce_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bot',
            name='bot_bot_bot_id_d44bce_idx',
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['owner', 'bot_id'], name='bot_bot_owner_i_aaa1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['owner', 'ai_model'], name='bot_bot_owner_i_fd28c8_idx'),
        ),
    ]
